### ISSUE TITLE
Allow entering delay in HH:MM:SS format

### ISSUE THREAD

**Issue by rahmant3** [remram44/twitch-vod-sync#13]
This is a nice tool, thank you for making it. 

One suggestion: it would be a nice QoL improvement if a user could enter the delay in HH:MM:SS format. Right now it seems that the delay is entered in minutes.

**Comment by remram44** [comment]
Thanks! I'm surprised anyone found it TBH.

I'm tagging this hacktoberfest since it seems like an easy self-contained change that someone could do (as long as they know JavaScript, that is).

**Comment by PranjalAgni** [comment]
I would like to work on this issue

**Comment by mohammed786** [comment]
Hey @remram44 

I would like to take this up.

**Comment by remram44** [comment]
@mohammed786 as you can see it has been claimed already. There are other open issue though, and probably improvements that don't have tickets yet.

**Comment by PranjalAgni** [comment]
@remram44 Should I change the default behaviour and keep the format fixed like `HH:MM:SS`.

Few examples:

For 15M we need = 00:15:00
For 20 sec we need = 00:00:20

**Comment by remram44** [comment]
I think it would be nice for the "123" (seconds) format to still work. Additionally we could support "5min" / "5m" etc and turn that into the correct "00:05:00".

**Comment by PranjalAgni** [comment]
Okay so reiterating once again on the functionality:

Few examples:

"123" = Will be treated as seconds
"5m" = Will be treated as 5 minutes
"65m" = Will be treated as 01:05:00
"2h" = Will be treated as 2 hours
"01:00:00" = Will be treated as 1 hour

As the final time will be always represented in seconds, so there will be not much problem

**Comment by remram44** [comment]
Sounds great! Also don't forget that the time can be negative (prefix any of those formats with "-") to indicate that the stream is ahead, not delayed.

**Comment by PranjalAgni** [comment]
Sure I will take of care of negative number scenario

**Comment by PranjalAgni** [comment]
Can you help me setting up local development environment. I am basically stuck as the web app is running on `http://localhost:3000` and I am using my own `twitch client id` with redirect url as  `http://localhost:3000`. So I get stuck in the loop of authorization

**Comment by remram44** [comment]
You probably don't have to create your own application on Twitch, my own client ID should work.

If the app redirects you to `https://remram44.github.io/twitch-vod-sync/#access_token=...&scope=&token_type=bearer` you can just copy the part after the `#` and put it after `http://localhost:3000/#`

**Comment by PranjalAgni** [comment]
Nice it worked

**Comment by PranjalAgni** [comment]
When we enter time in `hh:mm:ss` it is finally converted to seconds so when `setstate` happens it changes the text on delay input box.

Example:

I entered this delay:
 
![image](https://user-images.githubusercontent.com/26196076/94951585-2f812b80-0502-11eb-846a-9a783481d11c.png)

It got turned to:

![image](https://user-images.githubusercontent.com/26196076/94951813-90a8ff00-0502-11eb-89dd-453556022f52.png)

Do we need this behaviour?

**Comment by remram44** [comment]
I would rather have it the other way, e.g. whatever you put in, it gets displayed in HH:MM:SS format. If you don't mind?

Otherwise I'm happy to merge in as is and do that later :smiley:

**Comment by PranjalAgni** [comment]
Sure I will do that change as well, its couple of more changes just 😃
