### ISSUE TITLE
repository has no license, cannot fork

### ISSUE THREAD

**Issue by jh0l** [remram44/twitch-vod-sync#19]
Hi I'd like to fork this project, possibly create a new product based off it but this repo has no license so it's illegal for me to do anything the code. Would you be so kind as to specify a license or state what can otherwise be done with your repo's code? Sorry if I'm being pedantic, I just don't want to straight up rip your code with no license to do so.

**Comment by remram44** [comment]
Oops!

I added the MIT license, since I have no plan to do anything serious with this. I'm sure that works for you :wink:

I built this because I wanted to use it (to watch Apex Legends competitions), so I might be interested in whatever you make from it. Don't hesitate to share some details!
